#!/usr/bin/env python3
"""
The rules of this repository, as code rather than prose.

AGENTS.md states these rules for humans and agents to read. This script is the
same rules executed, so a violation fails instead of relying on someone having
read the right paragraph. Every check below exists because the rule it enforces
was actually broken at least once.

    python3 tools/audit/invariants.py          # check
    python3 tools/audit/invariants.py --fix    # repair what is safely repairable

Exit 0 = clean. Exit 1 = at least one violation.

Standard library only, and the generator it invokes needs no third-party
packages either — so this runs identically on a laptop, in a pre-commit hook,
and on a CI runner with nothing installed.
"""
import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# Generated by assets/brand/make_readmes.py. Hand-editing one is a defect even
# when the prose is good: the next generator run destroys it silently.
GENERATED = ["AGENTS.md", "CLAUDE.md", "README.md"]
GENERATOR = Path("assets/brand/make_readmes.py")
BUILD_DIR = Path("build/readmes/MalikAI-786.github.io")

# This repository is public and deploys from main. Anything tracked is served.
FORBIDDEN = re.compile(
    r"(^|/)(__pycache__/|\.env($|\.)|id_rsa|id_dsa|credentials\.json"
    r"|service-account.*\.json|\.netrc)|\.(pyc|pem|key)$"
)

# Colour belongs in tokens.css. A budget rather than a ban, because a couple of
# literals genuinely cannot use a CSS variable — the count is what must not grow.
HEX_BUDGET = {
    "index.html": (1, "the theme-color meta tag; everything else uses tokens.css"),
    "newsletter.html": (1, "the theme-color meta tag"),
    "linkedin.html": (2, "theme-color plus the LinkedIn brand red"),
    # brand.html is exempt: it is the swatch reference page, so printing raw
    # token values is the entire point of it.
}

# Every method file states the same five things in the same order. The third is
# the one that matters: a technique described only by its strengths is a sales
# pitch, and this practice argues that a claim is worth what its evidence is.
METHOD_SECTIONS = ["What it is", "When it applies", "What it cannot do",
                   "Citation", "How I explain this"]

failures: list[tuple[str, str, str]] = []   # (rule, evidence, fix)


def fail(rule: str, evidence: str, fix: str) -> None:
    failures.append((rule, evidence, fix))


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, capture_output=True,
                          text=True).stdout.strip()


def check_generated_files(fix: bool) -> None:
    """Re-run the generator and compare. The check IS the rule, executed."""
    if not (ROOT / GENERATOR).exists():
        fail("generated files", f"{GENERATOR} not found", "restore the generator")
        return

    result = subprocess.run([sys.executable, str(GENERATOR)], cwd=ROOT,
                            capture_output=True, text=True)
    if result.returncode != 0:
        fail("generated files", f"generator exited {result.returncode}: "
             f"{result.stderr.strip()[:200]}", f"fix {GENERATOR}")
        return

    for name in GENERATED:
        root_file, built = ROOT / name, ROOT / BUILD_DIR / name
        if not built.exists():
            fail("generated files", f"{BUILD_DIR / name} was not produced",
                 f"check the REPOS manifest in {GENERATOR}")
            continue
        if not root_file.exists():
            fail("generated files", f"{name} is missing from the repo root",
                 f"cp {BUILD_DIR / name} {name}")
            continue
        if root_file.read_text() != built.read_text():
            if fix:
                shutil.copyfile(built, root_file)
                print(f"  fixed: {name} restored from the generator")
            else:
                fail("generated files",
                     f"{name} does not match what {GENERATOR.name} produces — "
                     "it was hand-edited, or the manifest changed without a rerun",
                     f"edit the REPOS manifest in {GENERATOR}, then rerun this "
                     "with --fix. Never hand-edit the file itself.")


def check_tracked_junk(fix: bool) -> None:
    """A public repo serves everything it tracks, including compiled artifacts."""
    hits = [p for p in git("ls-files").splitlines() if FORBIDDEN.search(p)]
    for path in hits:
        if fix:
            subprocess.run(["git", "rm", "--cached", "-q", path], cwd=ROOT)
            print(f"  fixed: untracked {path}")
        else:
            fail("tracked junk", f"{path} is tracked in a public repo",
                 f"git rm --cached {path}   (.gitignore does not untrack an "
                 "already-tracked file)")


def check_nojekyll(fix: bool) -> None:
    """Without it, Pages hides paths beginning with an underscore."""
    if not (ROOT / ".nojekyll").exists():
        if fix:
            (ROOT / ".nojekyll").touch()
            print("  fixed: created .nojekyll")
        else:
            fail(".nojekyll", ".nojekyll is missing",
                 "touch .nojekyll — Pages otherwise runs the site through Jekyll")


TOKENS_CSS = Path("assets/brand/tokens.css")
PALETTE_PY = Path("assets/brand/palette.py")

# CSS custom property -> the attribute name it must equal in palette.py.
# Everything on this list mirrors tokens.css by design (see palette.py's
# module docstring); anything not on it is a derived value with no CSS
# equivalent and is deliberately outside this check.
CSS_TO_PALETTE = {
    **{f"--ember-{n}": f"EMBER_{n}" for n in
       (50, 100, 200, 300, 400, 500, 600, 650, 700, 800, 900)},
    "--ember-tint": "EMBER_TINT",
    **{f"--ink-{n}": f"INK_{n}" for n in
       (950, 900, 800, 700, 600, 500, 300, 200, 100, 50)},
    "--paper": "PAPER",
    "--white": "WHITE",
    **{f"--verd-{n}": f"VERD_{n}" for n in (600, 500, 300)},
}


def check_palette_matches_css(_fix: bool) -> None:
    """palette.py exists so the generators stop typing hex by hand. It is
    only trustworthy if it cannot silently drift from the CSS it mirrors."""
    css_path, py_path = ROOT / TOKENS_CSS, ROOT / PALETTE_PY
    if not css_path.exists() or not py_path.exists():
        return   # nothing to compare yet; other checks cover missing files

    css_text = css_path.read_text()
    seen: dict[str, set[str]] = {}
    for name, value in re.findall(r"(--[a-z0-9-]+)\s*:\s*(#[0-9A-Fa-f]{6})\s*;",
                                   css_text):
        seen.setdefault(name, set()).add(value.upper())

    ns: dict[str, str] = {}
    exec(py_path.read_text(), ns)   # nosec — trusted, repo-local generator

    for css_var, attr in CSS_TO_PALETTE.items():
        if css_var not in seen:
            fail("palette drift", f"tokens.css no longer defines {css_var}",
                 f"either restore it in tokens.css or remove {attr} from "
                 f"{PALETTE_PY.name} and every generator that imports it")
            continue
        py_value = ns.get(attr)
        if py_value is None:
            fail("palette drift", f"{PALETTE_PY.name} has no {attr}",
                 f"add {attr} = \"{next(iter(seen[css_var]))}\" to "
                 f"{PALETTE_PY.name}")
        elif py_value.upper() not in seen[css_var]:
            fail("palette drift",
                 f"{css_var} is {sorted(seen[css_var])} in tokens.css but "
                 f"{attr} is {py_value!r} in {PALETTE_PY.name}",
                 f"one of them was edited without the other — make them agree")

    # --ink carries two literal values by design: light-mode text and
    # dark-mode text, set in different theme blocks rather than the ramp.
    ink_values = seen.get("--ink", set())
    for attr, label in (("INK_TEXT_LIGHT", "light"), ("INK_TEXT_DARK", "dark")):
        py_value = ns.get(attr, "").upper()
        if py_value and py_value not in ink_values:
            fail("palette drift",
                 f"{attr} ({py_value}) does not match any --ink value in "
                 f"tokens.css's {label} block ({sorted(ink_values)})",
                 "one of them was edited without the other — make them agree")


def check_tokens_json_fresh(fix: bool) -> None:
    """tokens.json is the portable export other tools read. Same rule as the
    READMEs: compare against what the generator produces right now, never
    trust a hand edit.

    Computed in-process rather than by running the script and diffing the
    file it writes — that would overwrite tokens.json on every plain check,
    even without --fix, masking exactly the drift this exists to catch."""
    import json as _json
    brand_dir = ROOT / "assets/brand"
    generator = brand_dir / "make_tokens_json.py"
    tokens_json = brand_dir / "tokens.json"
    if not generator.exists():
        return

    ns: dict[str, str] = {"__file__": str(generator)}
    old_path = sys.path[:]
    sys.path.insert(0, str(brand_dir))
    try:
        exec(compile(generator.read_text(), str(generator), "exec"), ns)
        fresh = _json.dumps(ns["build"](), indent=2, ensure_ascii=False) + "\n"
    except Exception as e:                      # generator itself is broken
        fail("tokens.json", f"generator raised {e!r}", f"fix {generator.name}")
        return
    finally:
        sys.path[:] = old_path

    if not tokens_json.exists():
        current = None
    else:
        current = tokens_json.read_text()

    if current != fresh:
        if fix:
            tokens_json.write_text(fresh)
            print("  fixed: tokens.json regenerated")
        else:
            fail("tokens.json",
                 "tokens.json does not match what make_tokens_json.py "
                 "produces from the current palette.py",
                 "run assets/brand/make_tokens_json.py, then commit the "
                 "result")


def check_hex_budget(_fix: bool) -> None:
    """New colour goes into tokens.css, not into a component rule."""
    for name, (budget, reason) in HEX_BUDGET.items():
        path = ROOT / name
        if not path.exists():
            continue
        found = sorted(set(re.findall(r"#[0-9A-Fa-f]{6}\b", path.read_text())))
        if len(found) > budget:
            fail("hex budget",
                 f"{name} has {len(found)} hardcoded colours, budget is "
                 f"{budget} ({reason}): {' '.join(found)}",
                 "move the new colour into assets/brand/tokens.css and "
                 "reference it as a variable")


def check_method_sections(_fix: bool) -> None:
    """A method described only by its strengths is a sales pitch.

    Every file under methods/qualitative/ carries the same five sections, in the
    same order. "What it cannot do" is the one that exists because it is the one
    a writer skips: malik-research already requires every model to state its own
    limits, and a method is no different.
    """
    for path in sorted((ROOT / "methods" / "qualitative").glob("*.md")):
        if path.name == "DESIGN.md":       # the study itself, not a method file
            continue
        text = path.read_text()
        missing = [h for h in METHOD_SECTIONS if f"## {h}" not in text]
        if missing:
            fail("method sections",
                 f"methods/qualitative/{path.name} is missing: "
                 f"{', '.join(missing)}",
                 "add the section — 'What it cannot do' is not optional")


def check_prompts_are_portable(_fix: bool) -> None:
    """A prompt that only works in one session dies when the session does.

    Every prompt declares its INPUTS and OUTPUTS so it can be pasted cold into
    any model, which is the whole point of keeping them as files.
    """
    for path in sorted((ROOT / "methods" / "prompts").glob("*.md")):
        text = path.read_text()
        for marker in ("INPUTS", "OUTPUTS"):
            if marker not in text:
                fail("prompt portability",
                     f"methods/prompts/{path.name} does not declare {marker}",
                     "add an INPUTS/OUTPUTS block so the prompt runs standalone")


def check_citations_resolve(_fix: bool) -> None:
    """A citation that goes nowhere is worse than no citation.

    Every surname cited in a method file must appear in BIBLIOGRAPHY.md. Checks
    attribution, not page numbers — the bibliography says itself that no page
    number goes in unread.
    """
    bib = ROOT / "methods" / "BIBLIOGRAPHY.md"
    if not bib.exists():
        fail("citations", "methods/BIBLIOGRAPHY.md is missing",
             "create it; every method file cites into it")
        return
    bib_text = bib.read_text()
    for path in sorted((ROOT / "methods").rglob("*.md")):
        if path.name in ("BIBLIOGRAPHY.md", "README.md", "RUNBOOK.md"):
            continue
        body = path.read_text()
        section = body.split("## Citation", 1)
        if len(section) < 2:
            continue
        names = re.findall(r"\b([A-Z][a-z]{3,})\b(?=\s*(?:&|,|\(|;|\.))",
                           section[1].split("\n##", 1)[0])
        for name in sorted(set(names)):
            if name in ("See", "The", "Sage", "Anthropic") or name in bib_text:
                continue
            fail("citations",
                 f"{path.relative_to(ROOT)} cites '{name}', absent from "
                 f"methods/BIBLIOGRAPHY.md",
                 f"add {name} to the bibliography, or drop the citation")


def check_no_participant_data(_fix: bool) -> None:
    """methods/ is public. Participant data lives in malik-research, private.

    Under IRB-25-0462 a participant response in a public repository is not a
    tidiness problem, so this looks for the shapes such a file takes rather than
    trusting that nobody will paste one.
    """
    shapes = re.compile(
        r"(^|\n)\s*(P\d{1,3}|Participant \d+|Interviewee \d+|R\d{1,3})\s*[:—-]"
        r"|\btranscript of\b|\bconsent form signed\b", re.IGNORECASE)
    for path in sorted((ROOT / "methods").rglob("*.md")):
        m = shapes.search(path.read_text())
        if m:
            fail("no participant data",
                 f"{path.relative_to(ROOT)} contains something shaped like a "
                 f"participant response: {m.group(0).strip()[:60]!r}",
                 "move it to malik-research; methods/ is public and carries "
                 "method only")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--fix", action="store_true",
                    help="Repair what is safely repairable, then re-check.")
    args = ap.parse_args()

    checks = [check_generated_files, check_tracked_junk, check_nojekyll,
              check_hex_budget, check_palette_matches_css,
              check_tokens_json_fresh, check_method_sections,
              check_prompts_are_portable, check_citations_resolve,
              check_no_participant_data]

    if args.fix:
        print("Repairing…")
        for check in checks:
            check(True)
        failures.clear()

    for check in checks:
        check(False)

    if not failures:
        print("Invariants hold.")
        return 0

    print(f"\n{len(failures)} violation(s):\n", file=sys.stderr)
    for rule, evidence, fix in failures:
        print(f"  [{rule}]", file=sys.stderr)
        print(f"    {evidence}", file=sys.stderr)
        print(f"    fix: {fix}\n", file=sys.stderr)
    print("These are the rules in AGENTS.md, executed. If a rule is wrong, "
          "change it here and there together.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
