'use strict';
const options={occasion:['interview','networking','celebration'],format:['inperson','video'],dress:['business','smart','relaxed'],style:['tailored','fluid','traditional'],weather:['mild','warm','cool'],time:['5','15','30']};
const defaults={occasion:'interview',format:'inperson',dress:'business',style:'tailored',weather:'mild',time:'15',coverage:false};
function validate(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('A brief object is required.');for(const [key,values] of Object.entries(options))if(!values.includes(input[key]))throw new Error('Invalid '+key);if(typeof input.coverage!=='boolean')throw new Error('Coverage must be true or false.');if(Object.keys(input).some(k=>!Object.hasOwn(defaults,k)))throw new Error('Unknown brief field.');return {...input};}
function makePlan(raw){const b=validate(raw);const occasions={interview:'interview',networking:'networking event',celebration:'celebration'};const outfits={tailored:{business:'A coordinated suit or blazer and matching trousers, a simple top, and polished comfortable shoes.',smart:'A structured jacket or cardigan, a simple top, and well-fitting trousers or a skirt.',relaxed:'A clean knit or shirt, comfortable trousers, and tidy everyday shoes.'},fluid:{business:'A structured long jacket over a simple dress or flowing separates, with comfortable formal shoes.',smart:'A relaxed blouse or knit with a flowing skirt or wide-leg trousers and a light layer.',relaxed:'A soft top with easy-fitting trousers or a comfortable dress and familiar shoes.'},traditional:{business:'Your preferred formal traditional outfit, freshly pressed, with coordinated comfortable footwear.',smart:'Your preferred traditional separates with a simple outer layer and coordinated footwear.',relaxed:'A comfortable everyday traditional outfit with clean, familiar footwear.'}};
const tips=[b.format==='video'?'Place your camera at eye level and light your face from the front. Test how the outfit looks on camera.':'Try sitting, standing, and walking in the full outfit. Choose shoes you can comfortably wear for the whole event.',b.weather==='warm'?'Choose breathable fabrics and a removable layer if the venue has air conditioning.':b.weather==='cool'?'Add a removable warm layer and weather-appropriate footwear. Bring an umbrella if rain is expected.':'Use a light, removable layer for changes in indoor temperature.',b.coverage?'Choose opaque fabrics and your preferred sleeve and hem lengths; check comfort when sitting and reaching.':'Keep the fit comfortable and let your own preferred level of coverage guide the final choice.'];
const checks=['Choose a clean outfit you already own.','Check visible creases, lint, and footwear.','Arrange your hair or head covering as you prefer.'];if(b.time!=='5')checks.push(b.format==='video'?'Test the camera, lighting, and background.':'Lay out your bag and any event essentials.');if(b.time==='30')checks.push('Try the full outfit and prepare one backup layer.');
return {brief:b,title:'Ready for your '+occasions[b.occasion],look:b.dress==='business'?'Composed & coordinated':b.dress==='smart'?'Polished & approachable':'Comfortable & considered',outfit:outfits[b.style][b.dress],why:(b.occasion==='interview'?'A coordinated outfit can reduce last-minute decisions so you can focus on the conversation.':b.occasion==='networking'?'Comfortable, considered pieces let you move between conversations with less fuss.':'A familiar, comfortable outfit leaves more attention for the people and occasion.')+' Follow the host’s actual dress code; these are flexible suggestions.',tips,checks};}
let current=makePlan(defaults);const $=id=>document.getElementById(id);
function readBrief(){const b={};for(const k of Object.keys(options))b[k]=$(k).value;b.coverage=$('coverage').checked;return b;}
function render(plan,example=false){current=plan;$('plan-title').textContent=plan.title;$('look-title').textContent=plan.look;$('outfit').textContent=plan.outfit;$('why').textContent=plan.why;$('context').textContent=plan.brief.time+'-minute preparation · '+(plan.brief.format==='video'?'Video call':'In person');$('plan-state').textContent=example?'Example · edit your brief':'Updated from your brief';$('tips').replaceChildren(...plan.tips.map((t,i)=>{const row=document.createElement('div');row.className='tip';const n=document.createElement('span');n.textContent='0'+(i+1);const p=document.createElement('p');p.textContent=t;row.append(n,p);return row;}));$('checklist').replaceChildren(...plan.checks.map(t=>{const l=document.createElement('label');l.className='check';const c=document.createElement('input');c.type='checkbox';const s=document.createElement('span');s.textContent=t;c.addEventListener('change',updateProgress);l.append(c,s);return l;}));updateProgress();$('notice').textContent='';$('feedback-form').reset();$('feedback-status').textContent='';}
function updateProgress(){$('progress').textContent=$('checklist').querySelectorAll(':checked').length+' / '+current.checks.length+' ready';}
function saveText(name,text,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function snapshot(){return {...current,completed:[...$('checklist').querySelectorAll('input')].map(c=>c.checked),engine:'rules-v1',scope:'Provisional; original 22-point plan unavailable'};}
$('brief').addEventListener('submit',e=>{e.preventDefault();render(makePlan(readBrief()));$('notice').textContent='Your plan is ready.';});
$('brief').addEventListener('change',()=>{$('plan-state').textContent='Brief changed · rebuild to update';});
$('download').addEventListener('click',()=>{const s=snapshot();saveText('presence-plan.txt',[s.title,'Rule-based prototype | '+s.brief.time+' minutes',s.outfit,'Why: '+s.why,...s.tips,...s.checks.map((t,i)=>(s.completed[i]?'[x] ':'[ ] ')+t)].join('\n\n'));$('notice').textContent='Plan download prepared.';});
$('reset').addEventListener('click',()=>{$('brief').reset();render(makePlan(defaults),true);$('notice').textContent='Restored the example and cleared feedback.';});
$('feedback-form').addEventListener('submit',e=>{e.preventDefault();saveText('presence-feedback.json',JSON.stringify({plan:snapshot(),rating:$('rating').value,comment:$('comment').value},null,2),'application/json');$('feedback-status').textContent='Feedback download prepared. Nothing was sent; share the file yourself.';});
render(current,true);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'generate_appearance_plan',description:'Validate a complete style brief, update the visible plan, and clear the prior checklist and feedback.',inputSchema:{type:'object',properties:{...Object.fromEntries(Object.entries(options).map(([k,v])=>[k,{type:'string',enum:v}])),coverage:{type:'boolean'}},required:Object.keys(defaults),additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const b=validate(input);for(const k of Object.keys(options))$(k).value=b[k];$('coverage').checked=b.coverage;render(makePlan(b));return current;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
